[package]
name = "KingCrab"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
if_chain = "1.0.2"
num_enum = "0.7.3"
rand = "0.9.0"
ort = "1.15.2"
ndarray= "0.15.6"
rand_chacha = "0.9.0"
